### ISSUE TITLE
Code for Germany Interview with you - at CfA Summit or <where are you> ?

### ISSUE THREAD

**Issue by digisus** [max-mapper/messages#11]
Hi Max,
This is Marcus, OKF Germany board member and on the Code for Germany team. I will do a series of interviews starting at the CfA Summit in SF in two weeks and also visit Mexico (incl ConDatos conf)/Boston/Philly/NYC right afterwards.
I would love to interview you at either of these places. :-) The main goal of the interviews is to understand how successful community-city interaction got established in these cities and what good practices we should suggest to German cities. Of course, I am also very keen on talking about USODI and other cool projects your are working on. Will you be in SF for CfA Summit? Alternatively, are you located in any of the cities mentioned above? ;-) (Would be cool to do the interview face-to-face rather than online.)
Thanks & regards from Germany, 
Marcus

**Comment by max-mapper** [comment]
Awesome! I will be in Oakland during that time, and was going to come into SF for the CfA summit for one of the days. I just followed you on twitter, feel free to DM me when you're in SF and we can figure out a time and place. You're also welcome to take the BART over to east bay and we can get some tacos.
