### ISSUE TITLE
Taipei!

### ISSUE THREAD

**Issue by SwartzCr** [max-mapper/messages#21]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v1.1.3
Comment: https://keybase.io/crypto

wcFMA86+sofFUjedARAAvyCLEZkhkupglNM6yvfOW5XseSxYv+dt0vh811fupcxy
vWNeAEFR3CMz+dllVhG1Ss5Cr1+Y8BjiKdh87JCZgO2EALp0f1R2KkiSHymsoq+B
YRu4seh0sojkxoyc/Vts8VE1Fn9jGmxSZnKqF0Y7Ilw3UWjENybBSXzedgTjIYEn
FuUCE0PEQ7T7bxi+QQHqBEuqaN1UKsQJqlOpRw8XdbZ2J+0KS9Cjgelb/hwioFry
d+YLFT1KGfImXkrNb+DolUJs5Cm76drX066I9ILpBG0WISfUs8gcelp4prIfhxjl
NEvsuIEAp78oXKUaWZUbU9acLqPHCX5i6K5Q4HANIsPzNYa8D8274schOJR6eAZn
3qbZGlfXzwaCxM0Kc12yvx5saJMoEKf4lP4BRpKUBbDdUWPctRSZ6svZr6j+woE1
uEUDgc1342WkJJ7FnnLWeO9oSvWjzKwpeGSt1s0R/5edzBRLXIcRbq88H/Q2fwIr
4q7NERW8iC+yeTCoLSNyrt8oEMvdP7xpxyGYjd2OgD3xz5BxXfItdauTCUMsm1lJ
mknaFhY0SBzMJ/wCLXYQJBelgxMakwxZwILS1Nz+fCRLbSbug8vdS7f8XnWh+847
LzyCACULTQ/+9hvbqul9eh1qHGa5PN5FHC7f72LwvGkXjJYNuPTWgon9DSRUuD7S
0NYBt+UyrIo/74rWw3mUe7okyOgqHJrzsprKL1Wgwje5Rr0Rs3W4MZrsny5uUANi
AU7At8d678td4U3ZC3KWQHEToLhs/vCrh8N5Ad9a1cB3MBW4NaTe77Q08aF2P7zL
9H06oJehRWpojA+DhpSMWwPQBl0IKTsII7EG8CS4+SjGWuxnwYMB0zUeRVIGWgCm
mAk9I1aVlaS4WaQ4+yPUpDfFt19PRA+I177AIReTZjog5owI+M7tnG8Vp/FcnxTU
cQuN+nxf3xjbaL8gHBKi/nhGOezGBeINFlpidZI+vUsWhuMFYXKkSv4wJIWykIxm
qVqvYZ/lZbizpe5C3K1vj/q6G2kyljH3QH71j5cFkb+utJ78eDoUl4VCx5dnk3PP
03ldoq7ncMox/cx81ds107ryd2q/54ke86YTvT81tI2jnw0n7HiT+XSiDuhXrRxi
KKSWNAZKR//78uqqEiMexelRHSt/uQRQBwjQpLNbTCvhkVPy8M2/Dju/XASAwFSg
gtgV3o91R5T/QizODX0ZTx9PkPIohFlUS+rjNDb6ivNDPPYnKMNhfFn8ysB0KcKR
kVd1e6EepbNtOnmthHF3qwE2lqokt2THIn/W3bdrFXxmBYV5+sRN7CchifYOHhkn
sCiMzDMdtYtiDgGK3keg8oli654bpDElF7k020LP7Icfh4SXkV5lKNXDRP3j2qRO
EGR/iWM0iv+RSPtANnKnVZxBByGw0uQhJb4GyNXYlM5icFTkvvGKtPvYitsgLBDt
sgCBnEBYbUGwIcKatf60aGBK2CP5zeet8hKTgn4QlHXhsbNF0KodRLsmCXVn5viX
U3fo3y9BicomD672GsNkmfYTBdCNRr5wh79T2euP8MAg7FjJndMMxw177Kw/R9wc
7xeDylnI1PgVsXmiidWHaAiAIMol10S6qm07+MO7c4vO/gokEKZAZaW0BUlHiTM6
uIr6BX8odkxf8ooCf3eI45IB2SDPyzffG6O+/Ez2CMEGrPnwiJnvafSqqlCiwJvQ
AS2Ta9jO+Oqes8SJlfPHjeocg0T/sSeHta8asux+c2inLfBIedQbE6LRwNg5kd5u
sG0230xZNb1eB/kCQPFhAnmHUtDlMB54qWS5wpMyha1Hhz4u/fSo1IjBrraVrZMK
5BFXDBlUEj0aE6/Gpd3ChbXadZ+qWv+NqAkbKz10kE+oGmggn2o3WLxZurb0E4cA
EkCoSLk+TkjHS7C913ljU2moKj6jEZLgOyS8plqHoEQskFK3dqMwOu2ZFmKpfsnV
ANsb+t5MSs6PCgzd4bPXtsTKjihAk3UEGSTKvFHC7OS100ivcub/IlYDKxrAVelz
2g5d2EyzAQEl1qc88nL3aIeIHxspjAgtLkwTksAoTev/rxvzw0/otXV+D4PCKFmE
J1INItnz6KUJXC781J1GJ3bu7Nmb00WdwC1tl4w/C/cHqn+aPHGIZTeUw1XCsyJ9
Z1z5gcKT8hve2toDTRHpMZRwfpgp4DLzrRzLU0KZQwyBK8B/TM51Kd37atCT0WI9
5uLKqtPYLhT8+G0uK+jglYBgWKlDJ2zjARkYM7zn2spxgCgQpHEltS8xvqrNRnVP
Ka0+R2wgABo0R9R7hx1aXkFT3UY5Z5XCd0nr3Mz6bDmqOuAEWjhMTVOLl5utwtK9
jlNTVhV/MgUXQv60zXuIzqNOVfY5YWnbYwSMeBJoNneBw/4LhSH76CUPRBLuvwIE
qUqMPt0aSZlWdEobYRMwXDAisMIzJ7ItHIgv1Re/ugjxeR9pSe2cBqlJryhXgMo9
hiM/dOM7EGfWcg6P5c/VgOsqDGMzhiL8mmCXFPuDNRafx4TLKrWt8rbL7+L5nB3k
OafDO9+bVR2uxk3y2lNYyXImfdtzxi1IEzSgpI4JNVNP9uCbWWDhmzn/i52y98B3
6j10fuaXw7lMVnGHMBoQRTecNRSk9cUfbACwHTrJV//imCkPB9tVpfL8zjP3I6Si
JdLoYHHPYsyWlZ3Pmj6WZ8IT96eTKPgjp1baPjNn/AbO2+7mBRHXOdqTuxF4U4TF
6FriminYIu/T+EOOrNiKZqGt5jKpYt7vffQOcSW9v4IiOhX0Ebr47Ylkj/i/uIGV
5G2pm7XrtQ+iQpptR+06ttRMnY5vEUaEdxmEVZfrcMHvDYtF6v8KH45Z6/KEHr16
fALxzBqk8ZFCoBcvXOfMfdqOCN4akEgHI/ZJ2imdlFJzfW4246th6SEAsf+qQ4FN
QS9wK75EeYYccwNIZgJOqUw2mz19o++FhsZXYfDUcRdn8be44Si+NWlZfwSTBpIP
ZLxGqeSgn/7ejzrmVHGqGxHWRgAcOvKayYgu4v6/Yb7m92kOZCWQBQKs6P7FkZpe
AJ76A9sVXTVf9MGrv25wKkKCvX9/txRqsVVStBQCVexdveqVApA4c23CDFxIb1h1
R0DTHGDcLFltwrNrA1r/Jj0QPFibWMFYAZG0e+Q0WLSXwdpd4Ssr9SxjG9RrvMJ/
wOp/pTyUON4VIjH1TaFH12fqD/ouc8WAQPIOkdnMFI8lPSayKMYUNVTB/6giAO7q
r0r+6L+ZXsbW1DhBYvzqiSGD+18jAHiQ5l2f2YIS2IIivx9+gh7Br9KdVGB93eE+
/iqdfs4UDR3JxkbSMSha7zDJgr0yMrB6kY3NMJpwbEt1G9L+PfUSBDBmFvnSvBXd
eVKNbFzTYtzPLnBzdassOIE6goQB2G7F5f9Is+ue+KCw2tFjEURGFJE4gk+Myu5D
0+8t9bNl+7RbmBFYhBALhFSXjE8AsCv97tfXxrU2J6qDEEXqS/w05Gfhl8nMfQ4A
05RRSKPWqeqBkD4VIZlS2UUQ5HSroVYE9/5vNmMI2uY2oL2Qnfw5Xf30KBgT6q0S
f9ujMmzni6tapIEftquWogDcQMp/54A6RuodiavrySqnQoCWtcRU8FaF23PfCQyY
JfhoQ1WUzgvp3HUOZc0k4QnBavhA3K/XhH9QA+VbkbveD/pjT4SF/755ZvO0z/sk
vhOLdrHUiCzzy/0WcEEHz2EsQXXi9guYyjrE5BepAdk168v7J7rfnS23vEv/uU+C
mXSNd498DPQ/RRGb1WKBer1AYg9adrMXRtgmDmlFo5V0+KuCcIuLZTYhrVqYpnAw
h46i2RY5+3ZPfld1GT59G9VS7JGltgxETo+EAVdUxkDjq12aJz6dzUuBXK4luDr1
aFpymSDK+prqp+0EKOOzGF8hqAgrqjScEJ9QFfaEoHIh5QY2Y6GxO/qjbJgvr4MD
SaG+wBEm3AXDcYKTZJwfGKkNGMJHak9evE/Ig4C4hBoPLYnEWL4yDTvQkiCey0tU
nDZnf5BPlSrhAIaRi1wWX7T2UqPwYuDgvKYpctGSf190IWWD5Jn4ob8ggQc/iaVT
dllySetkshN3sOVtJPeg3QqWYITaxibCAWcB24IQ/7TyL7Ad5xRaYd6U8tJ/XMx1
MLnP3P9stIZg9xovRCqg+B0r/GD+ASvcPpFtCl6sF9m2AGy/vJx0rfb0BRs7BEH5
dhQrlMXwPQtfrj7mFh5ADrBoIZsQ+Rj56JGNuWlaKpwUJysd1S4ST1rwRPZOlt8M
4/OCOwJ6iPsXi7MxYS/0u+Lj2ascumJ9QRNVZo66+p2ZIsKk/5DJHEmUV3vFF/Xw
3Q3GoausbyV17uhXuN9rrntcJZ2kM0JWGg06n0EuKA/05I/o4OZfNxUTUBkhhuRe
VhKERJ8HTQS9EFxfOTzZjDW0j0NAMrbtztrJJdCRgNNPEpmEXN4xR6SO51PIqEOj
MT8sEYZPjOspBhBAtqr4f5IXEcU1zVhjtFz/1czUV3YkkMQlSw5x54C9XWo5BgeM
3PGJmz7Ly8cuH+QSf0/yAgVA/lM+pCsLfKu0HMk7nB6C9pCxvKpVePEymx0l1y8X
Bawzv7yGTkKYLWsOM1ki77oZ3rOjqgg9kCoNJRxs0Jy2IkqxqOzpwmjmRgW3Ft5v
ddQcb5N25YH+QCpQ1wPRuX5/WcnuEcrDuqfUWuHMWigr3ud8agLzBFbI1jKNMk/o
vDkbrYSjM9PZV6zBsPLcYLsHHg7yCIehy+53PeQZKOfnnWNiuf0MvVBpvE98fkRV
UkV8N9v4X4Xj+hA+CoeOu+vMnqrHW7ecxFKYtMe/+P14MW0cZukHiW7ecQ6WDVg5
T37TQTHWuCtpicM2CzuAgUpDOTKBccEhCFjOErHsW62cPR654RHqJXevgg7NSn3z
1BdqxGeBrjH8iEh5CsAGDC7+WPDSKSr2lWGAMWJCwsqG/iGPHaJyOmuZodwwhVd0
3Uu6Ljx8H/8kG+eB2+o8AqMw98NNtXFnTm4Xte702y8nzha5Ntn4kk2CoyfjC0FU
I8jxmKjYnUUdQFVx9f/tug+k9s3D7n9eCAAbCkufMRceGzfYTlCGKgO965RuITh/
kyr8rG19/KDPYmhIjoFWwbPcs4mRVRa/fI/TI3CCV0eprneI2BOogZZObBOJbkoX
z9n0+5WY3+hELcXIR+l/f8fV+c8rhbr/Kht+PQ9YyuX4or9xiDrd+MIkwfpr4BjO
9j5JQUiPOIzBvTNo5QxNE4HZ6PbTRxBGNqF/7Mu76BJWwYRLNnMcfF5xECkcvURi
wibL5AawKigpx/dl3iM2ZeG3qnLvAe9eb1ZGMJiw4Sgc/sRtHEh+lGO6iQ74P7dv
K9vEJQCLEIYGZOgfO7LvDIJ8lZFKZmNuLjSatA92u/LG7E9PxEEIHjjDp+8gQ9lz
jf+lhl+mJY7ByqXCn0oDDBqS4TnJ8n4qCBroY6YyNBdpjrxlhmH7DioK+Ab8Krwd
6CsTsXT6+cCe8N6BHonyw4Jby/zgWH3+fiYltfDpzERJwDpGFJud0dDIJgc2cHrH
Ind04hvT44mD2mocf92sKYeEjPV53hm0p9MHHBunW4jnswpb8zKpj1QS0QilXRkm
57Y39MldvLgTPGbMhFEYS6NYscun9f2JMg5f8MhYzjDuIXJZt4TZRCFrW9Q0b5Lp
63v+z8rMLhrJ9REW9z8kaRGO3I7j5kAZz8XBx8ze0uud3JfAsEthiwkTocsNKGd3
zOuwzBJOND/lpRMqum4xVBPclDs9TLQHaR9a4o7O388RJqNg03lj5vAiMXGleU6B
4F9mTF3qrzD7M2QAQ762LCNZvKJyjg09KTTGy0TbpSFntxLoESJ8ErP/THaKdBnk
2y3Rzr4QZ83kIWvh5Xh+1xgBYqV6LI8oUXBDLHbm4v7HImQKqIQRlvzvGrcQAfrc
KRzzdBGPi7K0EePfLfKsBdRXL7cQiYDOsQzoFgg6Hj+Pc6YE9PKp6NqOE/N+4pYc
jNTdnFiZh6b+/74d18WjRAZCNPA9Mkkr+dvlv4t9Yo5vGtDnOh9Or7aPedqe+IAG
mU7EVDRcjngcx6RvPZWLw3hXHSV2D2i/7vYzb7oqKPXBJF2XouardCcILOcPSS3N
xD1SiLRJTtEprhMECnc7aUr8s+WqHcGmtCezwYgxywt08Ob7lZSwLpeWHh2tAbYB
EKIWx4Tii0gUmA5xvn78toib2fi3VStXdxK8g4LYjRHoVVJEhsT2MzMiBGsnWxeT
dnNY4QiNTezvdsYRiiuFNWBjhgkyTfh4WjAs5qKxrLaFV0E4RYiTYCCxV85pmqCt
YLFCjfjulWJnB1ErRNpOj2ei+/Q3fA7GV7atIAj1zQ2R7ja9lo+6guuSx9sTQggZ
AhcXjgxWgUTTWN3vHAQ58NNKcszeJokvthh2QmS8UPRHAQtxiHhCxhHguSyB4vrQ
j2dtGwhrbvVf9q4Z1YA3bfzGuyqh9pY4PSro62PL6rsPFX9vDWhHsYgjbVKqFRt5
SC0i6Sril3Dr3LpdRFKAIYyA3skQLlAjFkGF1KKtGV/5QbksvLgOKZCAXFWhMesa
QNSledqSTQh9kJusO2wFr19t5IhghvXg/Sq22H02S6t6C1B28loM8z/Mf465Z99j
pyuNFaNSCot1Orn7ALarVLy7vWxkaAsMAcBcD7xZ3cPj4qcwhGXjDg==
=/pwz
-----END PGP MESSAGE-----

**Comment by max-mapper** [comment]
@SwartzCr lemme know if this works lol:

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQIMA1xp7ZeTRSo6AQ//ZTDwZamyZ+heyPGvUsEQXeVupO78uM3phkL618oqDXw2
H9Fae6FkoSu3Poo9Iwq71jvFPzMUcViQRkAcj+FG8/SmW7efIjYVy4uW1M/PJ6G0
ovwWu8us1fSHQrIvYX4wFQ886JywIMouiyD29SUX0OUyKtLpOzkgjCQbHv3vBAJ8
aX5aGn6t2wJIUBKrA/cmBW6XY3vyQrMsH3kZDHGxPudWzOtQNqtSlCGRutTzcjQh
7h7vOXQS/jby/aXDugRslMDYy+/eadIQdvM4Oqiejc7hIbUs2tNYB7ztbc+fT3pE
G7hvlX1JalGGooFCbfSxWv0Q1ZNPGZnCCIGCYK6yiKFgKRcN/KOFlt6r6adprcXW
ipem/aWl8pZu3V5XtFv6MDppEArwul7BfwAcfBf+KH7qKP279CD4H3YYLN03R8uE
IB7xkFfv0yRvGEbIamDNKFf+tqP2QPHqI5VfWQ9BtC6GuIel5Mph5jyogCQtRoy5
FVkVQSKo50HxI706csb/RL14Sdt56HhPI1qdZevYij4VWBE15RcLfjDyfS6PP4z9
vCsdAdakCBWcg4ao3jZP6rc+dewG62fOu6XTpC20cpjSYEfvEOt3m4oEBS51u/k8
VIJue9buLneTLyC8j0+udpIeVFNmVVWO7XJNMLPHe5CA1dGDZfEufjQQe5OKaY7S
6gG6eq+VkUsdv8bA34RO9z3/KrEIxjQHTV3keKJVZtbUd97LKZgzZYEdklP9ibE+
Jndv/q+SA7WAxOXdEFPI4dh8LHTbkKMR3YnTGVmgEwB9W2HGrZdk6cyJGsxamed5
FWwqdcxF/wsAgsDru7fOfoCFCCJe0/TqbEwSrDbKmf2ikcNAVNU4IIone02xOo/S
PjnQ54UWCl/DwfO9TV0wTIhptMHorV8vfDXGOveFZwOeykgZ/qWLUQ0GqNvoSsxa
kPUJrLJPT2go4kndE2pjbnolNxjCMj2a9eaevJgWgpgiCT8PjqUoimVPKk9aMxGv
mtWriWYPpfBpnl2a8OPxgRlhpxEydXBChuybDVpC4ApFQ9EkSULW/2b62PyLuHYs
U9JSxak34gGOZDeCpxsa+ecig34YNbxaaeFPYUTOmh41BK1AmDWkQgNIkkslU3xx
wVerMtNjGZpUc6VOF2Fys/g7u7Fq53DA3UJ1ZMAZzOJkRFRQ8H2BJuaiCsvYIujv
boU3zJScTNahwk837K/TqxCt6RKxjL75dV9af3CIp8Rt5F9ayCPq5CjGqkRJeSNe
yt8GsIG0UzPhU+coWNplCWigchQ7Oufaa9XyXyja8re7wlTqrsnC+uykQH+Wk/GR
Uuwe9pnSvoysfVEOswpDwYVGcHmAsOmaSC+VqRWNE3Y1lY324mRqrYWRqq7iTogI
hA280JjH47l3XrJDbUrWw1tZx5xq4UKeOpv+l7auHF96fQ6H1vS2WH3JoGpvgf9O
vO+psYsG5VXSvg20axOWNfFgphR+ArXVr/M+8ULiq9rwWWdZ6FVZWxq0T/jYCHho
5xMIaskS8oTVkLHxe9HSxrtTVtJRzI1LhDOZTGchlkrMXy8lcLPKfMKQUst7ITDU
3SBitd0z8RLY1vXNFUTqTRUC3NjVJIS5/pla6hWzail3mURr7rUkl85prZ6j0tvX
P2UNzCpXjphLq80Mt+epnbRAxnYFi3ZZnRRcxM1vKav1DU/UyjDzG/yKCBqXS+EH
kdNecrnaHRQeQ1NoiR3j3JIHsmiRsn/Qp/woxfGX49gM/ttqs7zaMPVS46CXP/Xs
0zCUHQ52D+Io6qmgIPy88DRueqRIFtit3HQA4vNE7ncHzuPupVptNWGBmGUTmkfc
dXQjX0Ro+PG6iq4UPTZBE2ZSr0oPMBZrie6YXWhkB4w1bHqXpwflcd4ACh15jHCE
NH1/zzz+6RMMAMtFyohhHD/SuKrg+zwWxV8/s3+dWy35MEpvQ79plHfkl//JIGBP
u1EH9FwRYy8J5d5SwLyyC/eARrdQS/H6WHZ2LIzbuEKc6GFg9du4R3wkS0glKOAq
9bYg80oir9soY1gavYRDbFtnMdpbCBOafsBxcYLrgeatJulop2cxon1uG688B1fl
L61yDr3DyFVO1U2CeM332KkaQ//2ngEntR2iZb+2dDuEa2zLIVYpGq/kN0ao/5Xg
55pRbWA7IFd797OG/0K9sVQteqLG3i3gDw==
=6ho4
-----END PGP MESSAGE-----
```

**Comment by SwartzCr** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v1.1.3
Comment: https://keybase.io/crypto

wcFMA86+sofFUjedAQ/+O+QZk3dN7uaWjrImqx6dij9y7Dw5POaLy8lbYTfIPzZ7
na1shP27Uywp9MNjRnA8f7oiwmYSaCQVjDE8Pe4P5DfRGpV7gRg++csrgSNwlYxS
XS+YAob0sgXrYNQtQ+eX7nyt4lcTW9h5u5rbJ/8BwdZ0XTOV161li975iMeujA+P
SnZxZ5l5ZvD9OMmrtchqLVKfB3UUZFKu0G/wtwmCIalZlHBl0ViZii1YFxG0E+PZ
zkt46ueWIx4LvY7n9wA38U3jpkjttJ++e7gmoLWZIbDad2Pvh1lgNgEKXf5l4JMA
i088xaxkqPsoAk7u1JH5jnSqdATqIcgKmZs0A8mHtFz3hDGyeNDHfikHpzBjGnqu
70PXlgkA9e+/0dtmyBsqWDPXJw6fAkT0TbaQgr9J7rLzGI+QFNIFLGaahXbd8whY
9GXv3rijBXhVWR7GlBTeEa8erwxZLLOQsQc0aW4kh5vxfqHzU28fcAbVXw3VYT0Q
vmuqIDbawysh7s555wXPC4AQtRZJH3EHaVPDAyQ5qtTRgZukMalVikG4Kv6Qui3O
zwoRno/JvZ4YOMjZSxoRHn8Yejjr81zXYZMlkl6z+xooEmMZNB6+chwMwtd6glba
SD2trkEkI65Ln+b/W0oZXh9ysUrWTFQo3n7LIf1T0hB1nQGk6/iFvdhgTjmtvYLS
wLMBvTyXx9WDU9pdnMfhMB4YOL3g18A8AN0dsklc75oscBFK8jQ1CxkPqVfMS8v6
yWxlrBIjoPnNmQBiLhEBqGUn6hd/31IbvZEGwwPaDpRJKbsJAERWj/TvxJWVKGYv
2vVAz/V3tlUyfHqVt6rbFLZ1Qe2qcx6leq9Fp+PfyNy1OXZq6YaLoNG0g5TpoF/0
X06hpbExS+10vx4A13zahugSEbR5J4/DTN7IWxi19NAyQkrIzg8OaYjCF3V4QqGj
7lEtZjnPmE181QCQZGLmkE/6CrT/Xj1pJBab8OJh5r7FqFChm/OJoecPTr5sOftI
YV8WeIvmi2wnWadgB/7049JDrIj4OaH0RXn7ElcW24Dl475xUm43f15ag6VNLleK
ARTpczCVhfukFb2pCkm3dWy0T2NG/1T0+hmvL4/UbAwFcRbeQw6nsaJjzXlhZTmS
BfwVN2h+SQDpRsq1/ZLGiV1/55BnP80pZEedEChoeAfRxbZUWw==
=uxZy
-----END PGP MESSAGE-----
