### ISSUE TITLE
Tokyo

### ISSUE THREAD

**Issue by martinheidegger** [max-mapper/messages#26]
Hello Max, I will be translating your presentation on Saturday. I will be in Tokyo from tomorrow around noon. Would be cool to get in touch before that. cheers!

**Comment by max-mapper** [comment]
@martinheidegger Hiya! I have just forked `learnyounode` from http://nodeschool.io/ and renamed it `learnyounode-jp` and added you as a collaborator:

https://github.com/maxogden/learnyounode-jp

The exercises that need translating are in the `exercises` folder, they are in markdown like this: https://github.com/maxogden/learnyounode-jp/blob/jp/exercises/baby_steps/problem.md

Here is the order of the workshops:

![screen shot 2014-11-13 at 10 49 17 pm](https://cloud.githubusercontent.com/assets/39759/5029168/56266996-6b87-11e4-832b-79e893edaaf3.png)

It is a lot to translate, so if you do not have time I would suggest trying to do the first 6 at least. Sorry I didn't let you know about this sooner. I'm free tomorrow, we can meet up at a coffee shop somewhere for sure. DM me on twitter when you are around and we can coordinate

**Comment by max-mapper** [comment]
Oh also if we have time I also wanted to offer a `levelmeup` in Japanese, as it would be suitable for more advanced attendees.

**Comment by max-mapper** [comment]
I also forked `browserify-adventure` and `levelmeup` at the request of @yuskesh and added both of you as collaborators

https://github.com/maxogden/browserify-adventure-jp
https://github.com/maxogden/levelmeup-jp

**Comment by martinheidegger** [comment]
Contacted you by Twitter dm

**Comment by yuskesh** [comment]
I will transrate browserify and levelmeup. Could you transrate
learnyounode, Martin?

**Comment by martinheidegger** [comment]
@yuskesh I translated the first 5 sections of learnyounode (as i mentioned in gitter.im) Lets continue the discussion there.
