### ISSUE TITLE
encrypted message

### ISSUE THREAD

**Issue by getify** [max-mapper/messages#36]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.1
Comment: https://keybase.io/crypto

wcFMA86+sofFUjedAQ//V97ftf/CJQpZw/fqiQJNbj7hqd/3EgX0ZHwxEWE/x31J
81QYIplkBpIgeMHyHiOAYj3NqVLBlqr1h4HT9WpQHIKqCeVploVFLnnOzkHjHINQ
v6wZ+xmiBlnNBONS1Pj40Lf6B2gBrACDp008lNw9tw0Pu3enxRDj9DUpBEVWpdkF
ulJfHyxreVALmBYXvN1kEufzGvWEF2KzNYPz6Hi3Xp5Px6aeIu0E3/lWnT/hGUj9
qj5aS8+F18SdonAXAJnZKOgEkEGephVMtwzV11FaAZNdBAqRzKlGxtoqPgq81x9/
B/ijQw8PA8sYhhxjyrSBv0g3sTMDTao31X87clrU9NPps5YSsdfv4NBSObIRuyx4
uwRMHtkwuBUM1a6y18Ndo6L2SlDWdywS490Zwk3lawYR28W+exkpMNTdv55W24Me
DxSnYj8MduI7orkIUvMj9ivT8G6JTL9CZGL9WoYVvIAm+omv4uC8N4HaNzUm9zpj
iwnlXfzIchkM3aV/td4QAkntJNnsD7dpdQ2YPhuiv5g5OoeCVE/f3+wuNLWvQhLi
xFk68Dg156ijScHLmWOSYClqBnLMoTmh2vFJqvu13dGNJDdXbb4vDpXQe5Lp+lRL
4CYU9OX6isp0ZsBCkx50t258excpETopR4TQGUKNQWlqSl33xuwtz/jKEBftRWjB
wEwDYHBrI77z4gIBB/9Xth+AxT772y8YlSogez1avznP2JiFKoQ18/jc598hM1g5
wxJxb1sLoFtXfUhyIZ+LTtwguelz0V36Fc2/1oxfYqpPnXQLacMSJj9fK7vxIFt6
OJ6ue1GQI3QzaiSPsPrTpAj9FHtrT2kVHJtfrBOCynoP3Akr/2+382bwoRF1+Qc/
GB23LZrFdzH7kUfWeuTqBVw74w3rdoLE+Y7oKVZvr2wBozhtuk1roIWxcx1DJRyu
wQkjTWHsDWa24Q1TgpVK/lGimU0N3M9V+kSbuwfiFlizspcQGYb6OUudQNeAO73B
z4qr35gNnqYi471/G/HVC3oCBgoOYLV8dL+HIr7U0sW0AV2y/2BrUD7c6zpZcEKN
zWb9Pz86LZslNxiQpOCFEPNYG3srnBzdBzJZcuczr3In8eMsVmG2pYQWbGPd57JX
fH2711EgCPfMmBhhOS9NMvAahA38L34lyQhlaPXZyBbF8mJ3WEMZYReK8mVxzW35
2mebLOdFQzp8rNE01pXOqP//hmSJ0QnN23Y0dYXrZoHfLGIyeS41JqKzUaIw5EGT
WgV04hloJhVadJpOYKBBZK6KYmRfDWpaToEsfNrUIn8zsu2PGsSq2ArU4icPDxgH
skcyFx9JggnMTEp73Rb0skgjzG6cynFxHtIfwuIi5QyyYBRCu+I1HAd+OMVfhTfs
rVTTk6ZH+Iy+1/+zOK4crMW6WgN8TmT+F0cU+7k/ZX1B+lDwRQ2TWMmH60SRVLGX
VRJbIc6IF6+1aiKi6R8VtiCb94EiktATW2oGELCkp0BvZOCU5jenqnii2iEM2OYN
MrzPIQO4ZDSLtW/28Fwm3llg/VvwB7v+YaLGOSJkPYbthFFd2K1zbTaKdZzxbbXF
F5T9KVmY+JhtypxEWTr8CnDJHhGy2ag0JdhXEqqjeuJhnszOUT/G6Iijuhhrdfxa
JBemRsa5VG751gHCvmFL0S37tlD6N3XaHYZDvc45FV6Xizh++VL6EoR5cy5fVD2o
NGO04nRE+6D49TBdhGkQat1QCvdylzl6skfQY0EhB1K9X4oz1CpdTclqF9ZYjTme
3Y47FkNuBT1oK9PZLbOYq4mNGc0RBwUj7kVTkh0kW4YszMk10QVHdx31EwMPYYOd
TXWRe/EljjRzx9iYY8HnbTVHaFwoDYS6JNKoNm7BthuGC8kZxcd8PwLsTKkOOXa4
nFRK4jxytsAebgfJWzOE47jJYSEebIZq8tRyzOwqm0bBEi7Vk4LfjMXHTabdo4VG
LbIDGa3Wpm8+RwNReN/gTUefyvelOo/ZuKYj8ZiCwdBvMWOZKLOxPpeS5GpKmJ+e
B5y7ArlB2td7BocWXDGAXkCoa/8JWK+/lnL4qFwkCO/2QXEEZZNrplWD1LymqClR
ffjoYPS3MgarInvB0/8rLUBtvlFqLBQlbrq0UksRdRKlLtYkOCnyHDhTqCiWdtlM
SV9lmRkfsSFHBlFaF53hO2Tn4ezqPf11XFlVQ1kpMd2ppTdh5OefkaAwIt5bX/6I
hXGRgPM7Q6NOI/uac0mmgdynd0XRqkDajEf5Zuz8I9PztGbDgaU2n6j1dAr1pW8g
PA5dPDxTTumLvdv+CJMJHnR2HgqGv2IHiITsPSJFSb7jWfz5bL0YT3ZYdMFhdDIs
R/7b6/YHjcgwkeG7o74fyN+QdpT7oycaBTFIcPwnHTJsPbHGO6UXynuIVP1J9Uwj
/G1iFNpJI/Mrce9wtQT1SwFN/El+E8Id6hV4o+rqc1CnEETCri0k3ML64ZcvzRwa
Z/IIdIJ3atnN5BFZODT5geVoFr4LvXc1ewb3PVPNDtnZHMMmH9+Fd2uilNEADBhG
wvrIaPxDahHqcVCmu95dcbR1e7enS8qAJXH80T75QN91iJ/M+1X3CmSMRJhvB9LE
ydKhxy9bVOx9Rawz2GfFPU0PVSoRH0p9XoZ02+3UmcOPPKwpHqDma+p2s/Eaq5a6
O7crGJbP49Wa+WKR6ctD9EXoMncFpnWAaV8eNTU++GPp3/44uey+uJ7tI1zbhv58
DTy3q5+FZvvXRX3jqEoVaWLpRS151XPVK/4MxSKX/YllzOS/Rpe6flKdm2g8aW1v
+Sa6ROkJinywfVSJj8PLh6+RcIzqWHiItiz3QmjWKNKa83g7OtvYY2U8pEulTayw
a/6TBGLCfYfcK5WoIiHeAeC0W2EXz/gRGdzsvHnUrQZWZhX7YIrwf+vWMk3NSsNR
EBTdop562SQ45n//6sfkRzfSCBOCwxgOROXUcq8PiCrKsTTx1Q3qfsHqE2OqlGaz
u1Z0+pzkHQlnRx9E19IwAZzIekCmiSfv2BMWzk0JhqMym83Pn1kpppsynbTJMrMq
0Qpaq71v5e+B79FKAbM1/gW001iyrzw7QdCLhCHsHuI2QIyRgNgOyzUl/MEKrtm7
6NZ/r/FXMg+l2fkEpaxa+9re19UFXghQLHndIlehklNSmpJHr+hTNM7m7A/ZZB65
dD0ialJuqVcO44J2+7XBLT4NzMqj2JVSv7x1anME4AJjoyyw6MMNILU9MpH/vmG7
f92iJKs=
=xfa8
-----END PGP MESSAGE-----

**Comment by max-mapper** [comment]
```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA2BwayO+8+ICAQf/Yy8TLAwUtHfKr4GMoGIm3jzmtYN2p9syxWQC6tWoILqI
8xNxH6ApW2cdlDikJS7cEFfxHNG5qqVPaWS+3lOvhXtV8a+u27W7ZeG/hqeCi/Qf
FEicvR3/qopWXXqNyxom7i/T/SSdwYeyBWCGxl9s8vDU+ojR1n20ETedIA+cqVaB
hgPlDFviQZsICVPH07J/12Gc34c1y0B7faYEmDmTcoSf29pohABD5mhPgXNPRfsc
/3aReUyWKgstexuxvh/dK22RIkF/yJe/rZlPmUCZBEmjcNJ2/mXwpD7c/3NMjDPy
vVI+KMn3fHLHosCN5N8vsinlIWKN26tQv3JdB+2G4dI/AV5C7Md5dBN8p5pysrJC
jROvvO8i/wRc0pWFiMuA5LpURHshg8MYZumSc//pGhL8F0eqhuQdYyCZ1BAz1gkd
=nGD/
-----END PGP MESSAGE-----
```

**Comment by max-mapper** [comment]
hmm if that doesnt work try this

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA2BwayO+8+ICAQgAkGUvnV97dq1MiZT+czWN2jyZDR8D0Jc+FKyEJP8RioFd
HrJpS+diVrKiwH/d52Wc2mge8rn0eoFT9gXxoZyNzYTTCjC/eHnBE92my2hrHrnu
3e6IVtVTdVEg1/BYtPoTSYvePKd/mH7nLQ2Z2z2NCKFrkHwpFI+sc4W4JMVNq0OO
PFNEuX9KE+wMQY3VxM16ipb1dDAQAuVs8uRjddFpG7ISvJQ5x1srS6LtmpqcZUdK
3qAOuw+XwnBN97BAtaSTYib5gpJC33gN5jkWnWiCaoBu2vFuVazwXCHfHBPQQQf0
7FiW9W26Uot619Qqt8YgzyX6dLltV0FGcZS5kcRC5NLAjwF8HqKiSrU0dySsIp18
73BEJ2zDdwDDbuRu9yAsK042oGWHA6J2tpvsjVYZ5Qjvt+95moUfo0TZGTFEWvPG
CKloXfWk/DwCpuN+MfUVbCJdygW06uSVmScrDq0xyaf2lFujT7qRBDp9hyhO214t
qlFCrcJcvcpNigTI/M9rp8goBjPNEXts9gVaVNpaUEQwUGZX4WNU8z4EB4OTQBfg
cSNFGMVXCOL1MxCVrvgm1/AHer5CX/kurKv3yNyMF2W8G+93FS9FvN2Zkx2znOxt
Uk6irTW0+eyBLJaQhOgJBHpzOQKbS8Or2lZrK+FtVW/PPp2HrSW2UXtOm+YimDrI
dMj9OxXmkOym3N4zYXpnXPJ5anycil0wX6Lgjf7oM2P/WnTaHCXA2Wz8ETNcjHJ8
v5azM7Vyvj+PjdX0HnOiZYSD4xTcDUfyJGtURzmXsVVJ
=6zWI
-----END PGP MESSAGE-----
```

**Comment by getify** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.1
Comment: https://keybase.io/crypto

wcFMA86+sofFUjedARAAzN/7pSO45zIOnOwTf7cUECT5YhRBxSJBytBFfJc528t+
e8ejGjpEsROA1eoBRjD69+J9zEOTJtv6SeONqet32syZKkG0sHQ31kd+SpxvoSHs
ZBFqf2Kg+6GlXr0KEc6dLixCRoLIQW2tOgJFWF0IJSFZf/JeI+PGnv9aaHdjETGP
u5CQDXSJzJzzwyM7sxjLyFYCISeuIzZrxbvxmVeLDRn13eWLlZHIGsVl8TG3c76r
Xm9jau5/u5IDtpsu90n6citC/mr6AgVGEMmYK00Cb8tnCU/9r9+dOHNKMXK9nEq5
T7IXji+zTatYt+1rTE9Xcd1i2B7AaGBYpTHkDciudRWWaVxp2Nsh4GyNHi4mA/dq
3xVqxizfnFW9DF4TzA5hmszuyGNtVmBQNFoZ0tGdj3pbAZwrRo0yWT8VuePkVmAg
iSdKt8mD5Wrtgsa241OyAJZ0mO0fCzU+Usj4C72MAqrML3vWw+3BgEOlVzcxrIJi
2sT24QhjuVq1Vmlhdkn84NKkDV7SSP5/FiArAv+Gy3igK5pXEJuG+zJ8N9zozzaE
17+n1I0NwL2yCO9rRZMyoiL0tiPNuQ/W6Ki2sZ2rCXoEWcCZehHJGmgarXKXZaSF
UR4ImgljCh0OJPuRA9l+mDQ6ns3DQQtpBD6bwlqUYHFa9nf5j0PJWRFMBEs/FcbB
wEwDYHBrI77z4gIBB/95ifME0TIukcOaXu09uJJG81TQudgvvIN5l2HkM1YZLvwV
burPw7bGAEO4T8dYcRG5N5UMDSxSDWUPwBW1OudpG6efiKGaSh8DhP0k5iCpaRWM
jMXF98uyYCQLN1FMVfhYgqLQdslXmlwA8zcWOF1rTTL1M8D9Ui6ulGxYZz5lM1yc
hvcgEyROUWeGpxH7kmfAIsT/2aQaFk6FVe5nJxK3+hBpLalJYVasBh9T7j0Y1TjM
rEUEX+6PO7sTOORASCR7DZIASm0nsbD3i3zKoZ1y5ZIGf9fbvOhYnkkJc1je9OQg
rj5FHkqJHthJqx6/VUQ6UcXLQDLnRzANsvcg94550sE2AVmoTGJ0o2lv2cmr4rrk
4FcU3ZX6pJmcd4o1+EY7p8EJ3jcetDGeb+Kp1zYGR0ejmTJM5pErJ4Vg7Q4QyYAi
Mdzy0k0FzTFt8rkUQdIVsEEj3TBW63Q7AR/W9jRG333iHirLsqcKKwpibls5Hx3r
9HCDzZ4KSNfvy7uh8TwkCGxbAvvc/Ll30fPz8vau1TjC0elqJTtwlOS5EVX2EOmE
GKUw+3CMORtoihuRtHWPj+T3jI0YHyl2mCx17uqJH/eBNNLDfeIwMS5RoOMaeOth
VfJtAoRE5FEXar6Y0L5eTt51Xj5Z5TkRCfSLJeVozX6hkKVEvy9rh8HYoE5H4+jA
7M71afE1rz4RHb7ZlSxOxyyOdSk5MUaf0hU5uYjuK4B0Bx30hT/uGa3MiGS4XpGq
sZv4bLOUaxd9XZUa1AWP5zIRdmUcnrK+5yccmLt0h9U19QNAYTu72PrKgkiBF7pn
wDuNJvmWNDvtcG7OOfN/xtJpiVaYm2k0ZmnntU3CoBMPaZl606BhIDKrXWybtWO+
wg77rq44csWRmyFCKwve02nCM+1RSTONR88at/5RLlInaEjY2rZhmahnU76svhgM
Pi+qDy62owgPcGOHxpI5rBiMoDGn+QZaU0ItYWrv9CE/hmJbtQBSxV8bXfR4dKS2
rS2NAcjd2A==
=O5zi
-----END PGP MESSAGE-----
