### ISSUE TITLE
dat + arcgis

### ISSUE THREAD

**Issue by ungoldman** [max-mapper/messages#37]
Hey Max, I was bouncing an idea off @meandavejustice for a new ArcGIS API that is not terrible and one of the ideas that seemed to make a lot of sense was to make each dataset a dat instance. When you've got some time want to grab a beverage of choice in a portland location of choice and chat about dat?

![](https://manboobz.files.wordpress.com/2014/12/tumblr_inline_nbwiyp3wjn1qech3p.gif)

**Comment by max-mapper** [comment]
YEA

**Comment by ungoldman** [comment]
thanks for dropping by with @karissa today! dat is dope, I hope we can help it grow.
