### ISSUE TITLE
you use github for messages!

### ISSUE THREAD

**Issue by mpnagle** [max-mapper/messages#4]
hi max!

it's nagle.

i went to devla.bs after you connected me to jose at oakland.js. thanks!

there's a woman there, francesca, who is working on building an app for people to crowdsource reporting environmental issues and learn about ways they can get resources to work on those problems.

it reminds me a lot of portland smells!

can i put you in touch with her somehow? i bet she would love to talk to you.

maybe you could email me at mpnagle at gmail dot com?

see you!

**Comment by max-mapper** [comment]
oh nice, yea i'll email you. I'll also be at oakland.js this wednesday
