### ISSUE TITLE
helping out with dat

### ISSUE THREAD

**Issue by anandthakker** [max-mapper/messages#43]
-----BEGIN PGP MESSAGE-----
Version: GnuPG/MacGPG2 v2.0.22 (Darwin)
Comment: GPGTools - https://gpgtools.org

hQIMA86+sofFUjedARAArl5eUZjYd1CgPKTWgGfMCZTLRnEQzh8V/ds/qu8fqpzk
ch3heFYnxSKX+qbvtKMJdQOO19LoF1Ya717yDb//mJWee6IO5/RsBC6zNR1v+m8+
pMR60lxqSnS/P21Ma8Ad1i/o1o4pPYLQYqgFGK6EZ03IAG+qwh9hzbLmqU3Oe+l0
Xuzz9yF5Ts26BLxhdcA/fbEpbtBe0QpyiKMRDAwDBHfCf5AFesJSKAiEDi/0YZXn
cx1l8y0YSHoWO/4bgipi1T5dj7j/El9hMXSP9HV2U1bvzDQun471cnJCrhJ+LP4h
7n9dq2TMSRM1jOW3Dcdeoem2Z1wb4hZjgXUsbDwfVrZNLqRiEThI94txMh907+i8
XQ0G/4K3Tkaa0G4BDwuCGhY5+uParoFXN5jMgM7w2NacB0SX6pA+8hp0dOfXlHVG
hcYBcBkTcnOEFRC3X1bvdfMM8jzqByiX5KUkuMlNNh7thSgHF/NOFb5DsnupSGbw
9Gy7k3lB2CJuGUs9dBdV0ZK0lOZIjFiOSdR9esEf1HGD1H/M/WDWmfWCJdrwH9gm
4yidVLe3KQxnEU/6QNKOZ4TObFt0ppACNjGL74hMzB5lJFzYU8c132l3xj1xC5jN
4rkf8Dq4EQr8naFROEwWcqbhpuGPlxbAc3pG3BqyeSIkpzT3QdzPCqHdpq9/J97S
6QFuSUfEgSWGnIvaTeW/AoHQmmqcfSTu771CIcTdic7Mm8O8MsUOWrGf2PKsEocP
FZIv5fzkNh5PthL/5uGs+hpvy6/1WwLYFJRwrUb6+aOW2YN1YWtlDyVFL2GiQ+Bp
VA9QZb8a2Y8TQ2LVQD17bN48Cj/YaOnsUE3zIJa+moMp8zC0ppXstZ0qlrf/q6cv
EkCCmEYvqFj78OrA6ll2VH8dlpMrH80bSKgGE6qJ5weL/1omfMjiwn1u1uy1pRvJ
sGz0aN6yyM1ewI7Cv1ZHzDqqLKVvlnqAz3Fn0sK6z4kXPIxddqDP2XMSZOT5NlrO
B/gwTzNFNWbRzz2dvqE2fhJabL4EYNHGZ04pABG4cKIricFI+Ror2kFKPvpHIbe5
/FQuxpQigptwDKD0jp4rqLw5jPtr6uCzfrZsGny0M6/LRGcw1wfrGFWFrq8FDoWr
SfQ5jyjY/2fVWf7h36bEpMnWFYhweGZp8O0iiqYko5j+IltVm/4YcWeYkkjnnk2b
ktlBJIxBXlf3xGBWp/ktE9e0J1iul0NOIPWdrJapzQBti+n5YD7Pd4barys+adIq
CARp4hLOJWqouvdLpSKVGRqG0uUhL/HgTYKPGSvutbu8yj6jldkqIVYYqqK2B8lq
k1Bf2rJDEM42MjE+t6OikSwPOF9oLqIz02I+ZCySoSW+k9OozNO451gSFkoCqGtk
28W1thkbJtv2qTjJFd1phYiwYYSxkiBUt/lPTPjsfnrZBIlVla4SbPtJYk1woi4c
PerOnCWEYKF+ahaI8meqIexJGtArFcmCoXOP9FQt5wqQn3SSimGL3ctyMLehTJW6
90Hm6x6+kOlQIskl/J7fDDp8Z8NgqOkwS/iTARd585obuTMX/A==
=DsDN
-----END PGP MESSAGE-----

Me: https://keybase.io/anandthakker

**Comment by max-mapper** [comment]
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA4lTrpJLNW62AQgAi5plqfr/uBE4AWhpEErJ+iRQAZkyoeoRaggX7OOxg/Yv
sdn/6hFQ63ADwtHUcQZzex3NY0mcECtv4dq8zcTIjAgh3Qjo/egT2URRDfvsnHGG
jj6Yazv4AO+74bFuCZEqypwJiHEYhAFqxVSnpDSs/oIelM13wbJESXIcKnEmmXsY
bt10fwK7y/Z/zXIu61NpmjKTWQQZjuVwpA2YimwYLAAQVroK6y2ldu1+X4zrOnil
18X4HKXLMKHhPG6X4eyhCLGnzvqQSmWIEqFPe4G+9QXbu/S7wCuapd5NPG37oNGl
kqC35r/TshDie2v6LdzwHsJPwSXbXVpIbbnixYIHT9LpAcWqDHRU/YkSdsTwGv2s
e41bL+mLdI8OWoi4ut+uFwX3Khr0Z2DZPWRo2NujT+226aA2vgiO7Do5RPZdQ6H+
ZJkeHRLhVlEU4TT4shMX0I2EqKzWPSxpX0sMDStatFZhqxM4SvFozbZmBUbcAz7K
qkHpOKvdytb5GeXPp6za14wxh1DqPySKFOssQb9Vajhfs+DaOQvD4g9pgFvQiVNI
bDInmyER8sdJb9hKQDsY9U82Y5AmKfv8BJSr6/Au3W/Q1TltrbMql8s829HixOU+
Nyfy4sdH+JxaaHpbuL4Ut48Na/jjCh52p5H+c9I+TUkvmS0Ko1o+CW9sJ9xOwzhm
mpBqPe9Xu6UNmn6/WSF4L3TPQl990Ate5f7uGExU9sojSjD31A9GVeOR9VLBeNCl
Y4tNa0zcnEfqVn8VZnZHPxvcoWCimi+b4VYpz1Ah0maaTl9ykI/PIfVSVnKGXe3Q
maBlXy71vZNBrGKNMVPvL+aYOyyuSD/NJWZlvBv7AwdW/weJ9tsSzd85Lvuefjyp
ixz6PcSJR7UamLTHn6Rf/ElRs4gQ7KNe3rYrz7gwn9AECbE/WDQX9KDsSm6GZEmA
QtQayO9FVZsNYkCzvWZkaGOnr9u+MoxTmyEVfL1SiwOCxlXwsahDaSlwhEfOga+J
+LmyACm6cNv09gnKN1k3KXIU0zloNGKO+CvhRZMsO99csitu8j4=
=4eVV
-----END PGP MESSAGE-----
