### ISSUE TITLE
pdx open data / civicapps refresh feedback

### ISSUE THREAD

**Issue by ungoldman** [max-mapper/messages#44]
Hello!

@ksmpdx (Kevin Martin of https://www.portlandoregon.gov/bps/) and I have been talking about an impending [CivicApps](http://civicapps.org/) refresh (as well as some possible opening up of http://www.portlandmaps.com/ APIs).

Kevin's looking for some early-stage feedback with a small group before opening it up more and I suggested we invite @maxogden, @Caged, and @catnik to talk about what the CivicApps team is working through right now and what an ideal open data site for the City of Portland might look like to us open data users and advocates.

@ksmpdx suggested 11am on Monday, April 13th, at the 4th floor of the Portland Building. @maxogden @Caged @catnik are you interested and would you be able to make that time?

**Comment by ungoldman** [comment]
I also nominate @davy to round out our impromptu panel! She's actively working with a large amount of NOAA data and would provide valuable insight into the developer experience of a government open data API. That brings the number of invited folks to 6 including @ksmpdx so I think that should be the cap to keeps things focused and productive and make sure everyone has a voice in the conversation.

**Comment by caged** [comment]
That time sounds good to me.  I very much appreciate @ksmpdx et al. for opening up the feedback process and @ngoldman for helping to make it happen!

**Comment by max-mapper** [comment]
I can't do the 13th, but I can do Tuesday the 14th

**Comment by ksmpdx** [comment]
Tuesday the 14th does not work for COP staff, unfortunately. How about 3pm on Wednesday the 15th? @ngoldman, @maxogden, @Caged, @catnik, @davy, would that work for you? Same location, 4th floor of the Portland Building. And closer to happy hour.

There will be 6-8 City folks there as well. The CivicApps "refresh" project team (web developers and GIS staff). A largish group, but our side will mostly be listening. I think it will work. If anyone has any qualms about a group that size, let me know and I can pare down.

The start of an ongoing conversation, hopefully. Looking forward to it.

**Comment by ungoldman** [comment]
:white_check_mark: 3pm on Wednesday 4/15 works for me.

**Comment by max-mapper** [comment]
me too!

**Comment by catnik** [comment]
I'll be there!

On Thursday, April 2, 2015, Max Ogden notifications@github.com wrote:

> me too!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maxogden/messages/issues/44#issuecomment-89032011.

## 

Catherine Nikolovski
Executive Director
503 407 2963

**Comment by ksmpdx** [comment]
OK. We're on for 3pm on Wed 4/15. Hope that works for @Caged and @davy as well. We'll meet in the architectural splendor of the Portland Building, 4th floor. I'll try to grab you as you get off the elevator, but if not, just check in with the reception desk. If anyone wants a calendar invite, email me and I'll pass along. Thanks in advance for the time!

**Comment by caged** [comment]
Sorry for the late reply, I've been out of town.  4/15 at 3pm works for me!

**Comment by ungoldman** [comment]
I talked to @davy and unfortunately she won't be able to make it, but other than that it sounds like everyone's confirmed. See y'all next Wednesday.

P.S. We've started doing a little homework on the content of `ftp://ftp02.portlandoregon.gov` here: https://github.com/CodeForPortland/data/issues/3

**Comment by caged** [comment]
Ahead of our meeting later,  I put together (hastily constructed!) a list that touches on some things I believe to be important.  Some might be outside of the scope of this particular project.

https://gist.github.com/Caged/81ed9c994200286dc317

**Comment by ungoldman** [comment]
Great write-up @Caged! I think you covered almost everything I wanted to say and a little more. I added a tiny bit in a comment on the gist.

**Comment by ksmpdx** [comment]
Yep... thanks @Caged for doing it. Also appreciate the adds, @ngoldman. I will circulate with City staff. Though there will be differences of opinion in the room, all your points are worthy of discussion (we'll be one big happy family of frustrated agreement when we talk metadata). Tag on a brief intro of where we are with the CivicApps refresh, and I think we have our agenda! Of course we'll never get through it all... :sweat_smile:

**Comment by caged** [comment]
I was really hoping to make it to this, but it seems I've caught a sudden and nasty cold.  In light of feeling miserable and not getting others sick, I'm going to sit this one out.   If anyone feels like taking notes, I would love to see them.  Good luck! :mask:

**Comment by ksmpdx** [comment]
I hear you. Getting over the same cold. Looking at [the agenda](https://dl.dropboxusercontent.com/u/2836837/open_data_agenda_150415.pdf), which I basically pulled from your list, there's really no way we get through it all in an hour. If we get through half I'll be surprised. So I imagine this will be the first of several conversations. I'll try to take good notes and post.

**Comment by ksmpdx** [comment]
Great meeting today. I'll post a summary here tomorrow. Think the next steps are fairly easy, will build some collaboration and momentum. Dig the idea of a GitHub developer/request/metadata repository for pdx open data.

**Comment by ungoldman** [comment]
Thanks for making this happen @ksmpdx! Very excited to see where this goes.

@Caged we'll catch you up soon, but here's something to chew on:

http://portlandmaps.com/metadata/index.cfm

That's 1,246 datasets that BPS & BTS could potentially make open, but they don't have the resources to release everything in the short term and a lot of the metadata needs improvement. We can help by identifying categories of data and specific datasets the local community needs or may want soon. There was also talk of contributing and collaborating more directly on metadata improvement and the data release process via a github project.

Lots more was talked about, I'll let @ksmpdx summarize and then add more from there. @catnik @maxogden @mafintosh also made it and may have further reflections and insights to contribute.

Thanks all

:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by ksmpdx** [comment]
No. @derekwmiller and I are members of the org, but @mquetel is the owner. We should loop him in.

**Comment by ksmpdx** [comment]
Sorry for the delay. Quick summary of the meeting last week. Lots of good discussion, which @ngoldman also summarized well above:
- City staff (Rick Nixon's eGov team) gave a quick overview of the CivicApps platform refresh (being built out in Drupal, maybe 70% complete, not a dedicated project so not many resources devoted);
- City staff (Matt Freid's Corporate GIS team) talked about plans to open data via esri's open data platform. This would capitalize on existing services and workflows, making it quick and easy to open up data (current workflow of getting stuff to ftp server is manual and tedious). Currently the City's central GIS data hub hosts about 1,200 datasets.
- Corporate GIS team also talked briefly about the PortlandMaps refresh (about to beta), which will mean much more GIS data hosted as ArcGIS Server services that could be opened up via the esri portal, available as shapefile/kml download and GeoJSON, Geoservice, etc. via an API.
- We discussed at length how to prioritize what datasets to release? Folks suggested a shared GitHub repo focused on open data accessible through CivicApps and other related platforms (example of the San Fran FOIA "request" repo was mentioned);
- Also discussed at length metadata. Lots of shared frustration. How to encourage internal City staff to document their data, how the outside community might contribute to metadata (think collaboration on this front, also via GitHub, is an excellent idea);
- Acknowledged that the initial focus of the refresh/expanding the amount of data available will focus on GIS data as we have some OOTB options for open publishing. Tabular data will come later.
- Discussion of opening up the CivicApps platform code, perhaps making it an open project (City expressed concern about managing the latter).

Think we ended the meeting with two action items:
1. City staff will investigate making the info on http://portlandmaps.com/metadata/index.cfm available via either a periodic dump from the underlying database, or via an API. This would provide a pretty comprehensive list of what's available, at least on the GIS side. We're working on this.
2. @ngoldman, @maxogden, @Caged, @catnik and other local developers would think through a shared repository for categorizing and prioritizing stuff on the list for release, perhaps addressing some of the metadata shortcomings, provide a forum for questions about City data, sharing knowledge, etc.

My quick summary. Sure I missed something, misremembered something else. Feel free to jump in with corrections . Bottom line, though, I think we left with the beginnings of a plan for collaboration, which is exciting (and likely necessary, given our resource constraints).

Next steps? Jump in with your thoughts. Thanks all!

**Comment by ksmpdx** [comment]
Think this checks off the first action item:

http://www.portlandmaps.com/metadata/index.cfm?&action=Search&n=0

Then use the layerId to query each one for json:
http://www.portlandmaps.com/metadata/index.cfm?&action=DisplayLayer&LayerID=53568&output=json

**Comment by ungoldman** [comment]
@ksmpdx++ woot

**Comment by ungoldman** [comment]
@ksmpdx just curious, is there any documentation out there for how this API functions?

**Comment by caged** [comment]
Thanks for the updates!  

> Bottom line, though, I think we left with the beginnings of a plan for collaboration, which is exciting (and likely necessary, given our resource constraints).

This is great news!

>  City staff (Rick Nixon's eGov team) gave a quick overview of the CivicApps platform refresh (being built out in Drupal, maybe 70% complete, not a dedicated project so not many resources devoted);

Is there an example of a city that has started a project like this and continues to do it well?  Could this platform ever foster the type of communication that's happening in this thread?  Will it be markedly better than a GitHub org? What need does a project like this fulfill?  (disclosure: I work for github) 

>  City staff (Matt Freid's Corporate GIS team) talked about plans to open data via esri's open data platform.

Sounds like a great way to use existing tech.  Would this be friendly to machines?  

>  Also discussed at length metadata. Lots of shared frustration. How to encourage internal City staff to document their data, how the outside community might contribute to metadata (think collaboration on this front, also via GitHub, is an excellent idea);

My guess is that this isn't isolated to Portland or Oregon agencies.  This is probably systemic to all agencies releasing data (federal and local);  We could create a simple guideline/spec for documenting datasets and try to get buy-in from other cities and agencies.   I think in the absence of shared guidelines, agencies will continue to do this differently (and poorly) from each other. 

> Acknowledged that the initial focus of the refresh/expanding the amount of data available will focus on GIS data as we have some OOTB options for open publishing. Tabular data will come later.

I hope there's continued discussion and focus on how to update and maintain the data and respond to feedback well into the future.

>  Think this checks off the first action item:

:star: this is great!

> @ngoldman, @maxogden, @Caged, @catnik and other local developers would think through a shared repository for categorizing and prioritizing stuff on the list for release

@ngoldman do you think this should be done through CodeForPortland or should we setup a different organization for this?  FWIW, I'm happy to get this group whatever it needs from GitHub.  Let me know if I can help out here.

**Comment by ungoldman** [comment]
@Caged I'd be happy to host any efforts on the @CodeForPortland org. There's also @pdxgis which @ksmpdx @derekwmiller and @mquetel are part of.

There's no @CityOfPortland org, which I think would be a nice way to unite public open source efforts for Portland across BPS, BTS, other departments and local agencies, and citizen developer/contributors such as us. Examples from other cities:
- https://github.com/cityofphiladelphia
- https://github.com/cityofchattanooga
- https://github.com/Chicago
- https://github.com/City-of-Bloomington
- https://github.com/City-of-Helsinki
- https://github.com/CityofOttawa
- https://github.com/CityOfBoston
- https://github.com/CityOfNewYork

many many more: https://github.com/search?q=city+of&type=Users

**Comment by ungoldman** [comment]
@jden (2014 CfA fellow) also recommended taking a look at https://government.github.com/

**Comment by caged** [comment]
>  There's no @CityOfPortland org, which I think would be a nice way to unite public open source efforts for Portland across BPS, BTS, other departments and local agencies, and citizen developer/contributors such as us. Examples from other cities:

Agree 100%! This would be great for both technical and symbolic reasons.   If there's anything I can do to help make this happen, let me know.  We could also register https://github.com/CityofMaxOgden :stuck_out_tongue: 

@ngoldman TIL there is a private best-practices community in https://github.com/government where other city leaders/developers/members are discussing issues and documenting best practices.  My guess is it's private as a means to make everyone feel more comfortable asking questions. I'm betting there was a discussion somewhere about that decision, I just need to find it or talk to the right people.

@ksmpdx I can add the bps email domain (and other local domains) to [this list](https://github.com/benbalter/gman/blob/master/config/domains.txt) if you're interested in joining that community.  Unfortunately for the others here, it looks like only folks with a gov email address can join.

**Comment by junosuarez** [comment]
:+1: for @cityofmaxogden

**Comment by junosuarez** [comment]
@Caged exactly - it's private to make the .govs feel more comfortable asking questions without fear of looking stupid. Anyone can join if you add an email address to a github account from one of these domains: https://github.com/benbalter/gman

**Comment by ksmpdx** [comment]
Finally jumping back in. First the questions/suggestions from @ngoldman.

> @ksmpdx just curious, is there any documentation out there for how this API functions?

Standard story, we put it together for internal use, no documentation. But it's pretty intuitive. Let me know if you have specific questions.

> There's no @CityOfPortland org, which I think would be a nice way to unite public open source efforts for Portland across BPS, BTS, other departments and local agencies, and citizen developer/contributors such as us.

Agreed. I'll talk to staff about setting one up (mainly a discussion about who will own, I think?). If anyone has any guidance from your experience with other cities, let me know.

Now to @Caged. Admit up front I'm no expert on any of this (learning as I go), so take everything I say with a grain of salt. :bowtie:

> Is there an example of a city that has started a project like this and continues to do it well? Could this platform ever foster the type of communication that's happening in this thread? Will it be markedly better than a GitHub org? What need does a project like this fulfill? (disclosure: I work for github)

It's a valid question. What we want is a single, one-stop shopping site/brand for regional open data. The data itself will be on different platforms hosted by different organizations -- City of Portland, Metro, TriMet, PSU, etc. -- but all accessible via CivicApps. Goal would be to meet the needs of the casual data user (i.e., researchers, students... currently the vast majority of data requests), web developers, and everyone in between. We are very open to using GitHub for communication, contributions by the community. Could we accomplish _everything_ through GitHub? Perhaps. Any examples from other cities?

> Sounds like a great way to use existing tech. Would this be friendly to machines?

We're actually investigating that now, exploring how to pull info from ArcGIS open data into CivicApps programmatically. Could be we create something tied to the unique layer ID, similar to the metadata API above. Here's an example of an ArcGIS open data layer: http://imap.maryland.opendata.arcgis.com/datasets/9d917714a08148319bc09805f7272d4f_1

> My guess is that this isn't isolated to Portland or Oregon agencies. This is probably systemic to all agencies releasing data (federal and local); We could create a simple guideline/spec for documenting datasets and try to get buy-in from other cities and agencies. I think in the absence of shared guidelines, agencies will continue to do this differently (and poorly) from each other.

There are existing [metadata specs](https://www.fgdc.gov/metadata) on the GIS side, for sure, but they are onerous. I think the City's approach of "what it is", "where it came from", and "what the attributes mean" is a good one. But the data/metadata is a classic chicken-and-egg problem. The more data we open up, the more data owners will be asked to document. But opening up data with poor documentation frustrates those on the receiving end. One option is to open up what we have and let the community help us fix the metadata problem over time. Prioritizing getting data and relevant APIs out in the wild, even if they are not fully documented.

> I hope there's continued discussion and focus on how to update and maintain the data and respond to feedback well into the future.

Agreed! Think this is where GitHub comes in. Fosters collaboration, opens up a dialog between those creating the data and those using it. No need to reinvent that wheel!

Not exactly sure where we go from here, but I'm thinking step one might be a City of Portland GitHub org. Others, let us know what you think. And thanks!

**Comment by ungoldman** [comment]
> One option is to open up what we have and let the community help us fix the metadata problem over time. Prioritizing getting data and relevant APIs out in the wild, even if they are not fully documented.

Yes! This please!

**Comment by ungoldman** [comment]
To expand on my previous comment I think it's more important to have the data out there than to have it be perfect. Finding a sustainable process and communication pipeline between data stewards and community members willing and able to help improve metadata (and the data itself) is also an important piece of the puzzle.

**Comment by ksmpdx** [comment]
@Caged, @ngoldman, do you know if it's possible for our existing City of Portland GitHub orgs (i.e., @pdxgis) to live under a generic @CityofPortland umbrella organization? Wondering what others have done.

**Comment by ungoldman** [comment]
@ksmpdx you can create a new @CityOfPortland org and transfer ownership of existing repos, but as far as I know you can't have orgs in orgs. I think the easiest thing to do is create the CoP org as a free account to focus the org on open projects and add owners from different agencies to encourage cross-collaboration. You can also make teams to deal with different read/write/admin permissions for different groups. @Caged does that sound accurate?

**Comment by ksmpdx** [comment]
https://github.com/CityofPortland

**Comment by ungoldman** [comment]
Awesome! Thanks @ksmpdx. I'll close this thread and open something on https://github.com/CityofPortland/pdxdata to keep the conversation going.

**Comment by ungoldman** [comment]
---> https://github.com/CityofPortland/pdxdata/issues/1
