### ISSUE TITLE
pdx js hacky funtimes

### ISSUE THREAD

**Issue by max-mapper** [max-mapper/messages#47]
hello gents.

the 25th, 26th and 27th are on for an impromptu hacking festival at my house

i can provide internet and habitation systems

feross arrives around midday on the 25th, so we might as well kick the thing off then

@groundwater @beaugunderson @feross @mafintosh @shama @ngoldman @chrisdickinson

**Comment by groundwater** [comment]
I arrive around 1pm Saturday. I'm in!

**Comment by ungoldman** [comment]
:+1: I live in PDX so I'm also in.

**Comment by beaugunderson** [comment]
@maxogden i'd said i was gonna come down saturday but turns out i'm required in seattle saturday night; does sunday->monday work?

**Comment by max-mapper** [comment]
if you wanna track the nerd herd join #nerdtracker on freenode and look for my foursquare checkins

**Comment by ungoldman** [comment]
:+1: great success
