### ISSUE TITLE
What do you think of scenevr?

### ISSUE THREAD

**Issue by bnolan** [max-mapper/messages#51]
Hey Max, have you had a look at [SceneVR](http://client.scenevr.com/)? It's my take on building a virtual world. I'm currently working on breaking it into smaller modules so that people can use parts of it without buying into the whole ecosystem, and making it interoperate with the web better. But, yeah, from your experience with voxel, I was wondering what you think about webGL virtual worlds? :)

**Comment by bnolan** [comment]
:'(

**Comment by max-mapper** [comment]
lol, sorry. I was in scenevr with dominictarr and substack a couple weeks back. I found a cat easter egg on a ledge. It was pretty cool! One of the hardest parts of voxel.js that I never quite figured out was how to do multiplayer physics and hit detection. I think if you can get those to 'feel' right then you will have a pretty good platform. So far what you have is pretty good!

**Comment by bnolan** [comment]
Hahaha ;)

I'm using cannon.js for physics on the client, and we have a branch where you can simulate some objects on the server. I use tween.js for interpolating between network updates (network runs at 5 or 10hz). Cannon doesn't have native support for voxel fields, and I'm not smart enough to hack on the internals of cannon, otherwise I would have already added voxel.js as an element to scenevr.
