### ISSUE TITLE
PDX NodeSchool International Day Organizers Hacking Party

### ISSUE THREAD

**Issue by max-mapper** [max-mapper/messages#52]
Hey all,

International day is coming up in 3 weeks:

![](http://nodeschool.io/images/international-day-logo.png)

I wanted to get together for the next two saturdays and hack on organizer stuff:
- Saturday, May 9th, 10-3 PM
- Saturday, May 16th, 12-3 PM (note: this is an updated time)

It will be at my house in SE Portland. I'll provide gigabit internet and snacks and we can hit up the food carts at 28th and Division close to my house for lunching.

Stuff to hack on:
- Stuff in the issue tracker: https://github.com/nodeschool/international-day/issues
- Writing new workshops for the event (e.g. `electron-workshop`)
- General community organizing brainstorming (e.g. https://github.com/nodeschool/international-day/issues/14)
- Planning a PDX event

cc @chrisdickinson @wraithan @ngoldman @bcomnes @nrn @nvcexploder

Also feel free to ping anyone else who might be interested, but lets keep this invite-only since its at my house.

**Comment by bcomnes** [comment]
cc @meandavejustice

Sounds rad!  I'll plan on coming

**Comment by nvcexploder** [comment]
Awesome! I may be able to stop by on Saturday!!! I want to help regardless.
So does @olizilla! :D

**Comment by ungoldman** [comment]
Might be on a farm in Washington this Saturday and helping an old lady move next Saturday. I'll try to swing by if I can! Would like to help either way.

**Comment by chrisdickinson** [comment]
SGTM. Would love to sprint on a new workshop / help out!

**Comment by meandavejustice** [comment]
This sounds good to me too, @chrisdickinson you expressed interest on creating an audio workshop with me at one point. I would totally be down for that.

**Comment by nrn** [comment]
Probably going to have to pass this Sat, but should be in for the next weekend and the day of the event.

**Comment by max-mapper** [comment]
alright this weekend peeps seemed busy so if you wanna hack I'll be hacking at cafes in SE. lemme know if you wanna meet up today. otherwise lets do this next Saturday

**Comment by olizilla** [comment]
Will there be tea & biscuits? @nvcexploder promised there'd be tea & biscuits.

**Comment by max-mapper** [comment]
@olizilla are you in portland now???? I indeed have tea and biscuits, but I should warn you: biscuits are different here

**Comment by olizilla** [comment]
That being the case I shall charter a galleon and be with you 10 days hence, to inspect this biscuit travesty... and NODESCHOOL!

**Comment by ungoldman** [comment]
@maxogden hey just planning my weekend, what time are y'all thinking of meeting up this Saturday? I should be free for a while after the brunching hour.

**Comment by ungoldman** [comment]
Oh right, the first message in this issue. :blush: 

> Saturday, May 16th, 10-3 PM

**Comment by max-mapper** [comment]
@ngoldman I think adjusting for brunching time is a good plan, so let's say 12-3

**Comment by ungoldman** [comment]
:+1: :egg:

**Comment by ungoldman** [comment]
progress >>> https://github.com/maxogden/messages/issues/41#issuecomment-101824149

**Comment by max-mapper** [comment]
HEY EVERYONE I am moving the hack party from SATURDAY to SUNDAY because of the Write The Docs Writing Day: http://www.writethedocs.org/conf/na/2015/writing-day/

I added a description to that page with the new details for the NodeSchool organizers party

**Comment by ungoldman** [comment]
Can't make it Sunday! Will be in Olympia for a cousin's college graduation ceremony. Hack well!

**Comment by bcomnes** [comment]
Is the Writing Day open to the public or do I need write the docs tickets?  Also, anyone down to do preparatory work today on this stuff?

**Comment by max-mapper** [comment]
The write the docs writing day thing is open to the public (in the sense
that if you invite your friends they can come).

Also I _just_ got to water ave coffee if you wanna come here and hack
