### ISSUE TITLE
Setting the path of Electron.app for electron-packager

### ISSUE THREAD

**Issue by rv2358** [max-mapper/messages#53]
Hi,
I installed Electron with npm. I now want to check in the Electron.app (with modifications to icon, name etc) into git. So I made a copy of Electron.app in another dir. How do i get electron-packager to use the Electron.app in my git directory vs the one in /usr/local/bin/node_modules/electron-prebuilt ?
Thanks

**Comment by max-mapper** [comment]
moved to this repo: https://github.com/maxogden/electron-packager/issues/23
