### ISSUE TITLE
Hey max!

### ISSUE THREAD

**Issue by okdistribute** [max-mapper/messages#6]
I just found your work through a friend, and curious to chat. I'm currently working at datapad.io but have been interested in open science/open data for quite some time.

I also live in Oakland.. would enjoy grabbing a beverage or a bite to eat soon in regards to your plans w/ dat.

**Comment by max-mapper** [comment]
@karissamck whoa very cool. I will be at http://oaklandjs.com/ tonight in case you are around, otherwise I work from coffee shops in Oakland and would be happy to meet up some time. DM me on twitter some weekday and we can grab coffee
