### ISSUE TITLE
Awesome job on dat. Is there a python wrapper yet?

### ISSUE THREAD

**Issue by kyleterry** [max-mapper/messages#8]
I have a service oriented IRC bot that uses JSON to communicate with services. I want to dump everything in dat for science. Is there a front-end you know of in Python (import dat)? Or should I just shell-out?

**Comment by max-mapper** [comment]
shelling out is the only way right now. the command `dat import --json` will stream stdin into dat and should work large or long-running import workloads

**Comment by kyleterry** [comment]
Thanks!
